#!/bin/bash

set -x

dotdir=$(cd $(dirname $0)/../ && pwd)

# Always link to .zprofile for all envs.
ln -sfn "$dotdir/.bash_profile" "$HOME/.zprofile"

if [ "$(uname -s)" = "Darwin" ]; then
  for file in $(find $dotdir -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".*.swp"); do
    f="$(basename $file)"
    ln -sfn $file $HOME/$f
  done
else
  if [[ "$HOME" == "/workspace" || "$CODESPACES" == "true" ]]; then
    wget https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb -O bat.deb
	  sudo dpkg -i bat.deb
	  rm bat.deb
  fi

  cat "$dotdir/.gitconfig" >> "$HOME/.gitconfig"
  ln -sfn "$dotdir/.aliases" "$HOME/.aliases"
  ln -sfn "$dotdir/.exports" "$HOME/.exports"

  # Login shell is currently broken in CODESPACES for some reason, so hack around it.
  if [[ "$CODESPACES" == "true" ]]; then
    cat "$dotdir/.bash_profile" | tee -a "$HOME/.bashrc"
  fi
fi
