#!/bin/bash

dotdir=$(cd $(dirname $0) && pwd)

if [ "$(uname -s)" = "Darwin" ]; then
  for file in $(find $(pwd) -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".*.swp"); do
    f="$(basename $file)"
    echo "ln -sfn $file $HOME/$f"
  done
else
  for file in $(find $(pwd) -name ".*" -not -name ".exports" -not -name ".gitconfig" -not -name ".gitignore" -not -name ".git" -not -name ".*.swp"); do
    f="$(basename $file)"
    echo "ln -sfn $file $HOME/$f"
  done

  cat .gitconfig.linux >> $HOME/.gitconfig
  ln -sfn "$dotdir/linux/.exports" "$HOME/.exports"
fi
