#!/bin/bash

if [ "$(uname -s)" = "Darwin" ]; then
	for file in $(find $(pwd) -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".*.swp"); do \
    	f=$(basename $file); \
		echo $file $HOME/$f; \
		ln -sfn $file $HOME/$f; \
	done;
else
	cat .gitconfig.linux >> $HOME/.gitconfig
	cp .bash_profile .aliases $HOME/
	cp .exports-dev $HOME/.exports
fi
